input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  # In Step 11 we will normalise @timestamp / drop noisy framework loggers.
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-%{[service]:-unknown}-%{+YYYY.MM.dd}"
  }
}
