plugins {
    id 'goose.spring-boot-conventions'
    id 'goose.testing-conventions'
}

description = 'AI Gateway — REST + Kafka entry point to AI providers.'

springBoot {
    mainClass = 'com.typedgoose.aigateway.AiGatewayApplication'
}

dependencies {
    implementation project(':services:shared-contracts')
    implementation project(':services:ai-gateway:ai-gateway-provider-openai')
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation libs.spring.cloud.starter.netflix.eureka.client

    testImplementation 'org.springframework.boot:spring-boot-webflux-test'
    testImplementation libs.reactor.test
}
